# Secrets used by order processor application.

apiVersion: v1
kind: Secret
metadata:
  name: cosmosdb-order-processor-secret
  namespace: default
data:
  CosmosDbConfig__Connection: <base64-encoded-connection-string-of-monitored-container-account>
  CosmosDbConfig__LeaseConnection: <base64-encoded-connection-string-of-lease-container-account>

---
# Deploy order processor application.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmosdb-order-processor
  namespace: default
spec:
  replicas: 1 # A replica is required to be up momentarily to initialize the change-feed.
  selector:
    matchLabels:
      app: cosmosdb-order-processor
  template:
    metadata:
      labels:
        app: cosmosdb-order-processor
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: cosmosdb-order-processor-secret
          image: jatinsanghvi/cosmosdb-order-processor:latest
          imagePullPolicy: Always
          name: cosmosdb-order-processor

---
# Create KEDA scaled object to scale order processor application.

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cosmosdb-order-processor-scaledobject
  namespace: default
spec:
  pollingInterval: 20
  scaleTargetRef:
    name: cosmosdb-order-processor
  triggers:
    - type: external
      metadata:
        scalerAddress: cosmosdb-scaler.default:4050
        connection: <connection-string-of-monitored-container-account>
        databaseId: StoreDatabase
        containerId: OrderContainer
        leaseConnection: <connection-string-of-lease-container-account>
        leaseContainerId: OrderProcessorLeases
        processorName: OrderProcessor
