# Create KEDA scaled object to scale order processor application.

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cosmosdb-order-processor-scaledobject
  namespace: default
spec:
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 20
  scaleTargetRef:
    name: cosmosdb-order-processor
  triggers:
    - type: external
      metadata:
        scalerAddress: cosmosdb-scaler.default:4050
        connectionFromEnv: CosmosDbConfig__Connection
        databaseId: StoreDatabase
        containerId: OrderContainer
        leaseConnectionFromEnv: CosmosDbConfig__LeaseConnection
        leaseDatabaseId: StoreDatabase
        leaseContainerId: OrderProcessorLeases
        processorName: OrderProcessor
        endpoint: "<>"
        leaseEndpoint: "<>"
        clientId: "145385f0-1987-4ffa-a9c5-a84731220641"
