# Deploy order processor application.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmosdb-order-generator
  namespace: default
spec:
  replicas: 1 # A replica is required to be up momentarily to initialize the change-feed.
  selector:
    matchLabels:
      app: cosmosdb-order-generator
  template:
    metadata:
      labels:
        app: cosmosdb-order-generator
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: <service-account-name>
      containers:
        - name: cosmosdb-order-generator
          image: <image-name>
          imagePullPolicy: Always
          env:
            - name: CosmosDbConfig__Connection
              value: "<endpoint or connection-string>"
            - name: CosmosDbConfig__LeaseConnection
              value: "<endpoint or connection-string>"
            - name: CosmosDbConfig__MsiClientId
              value: "<client-id>"
            - name: CosmosDbConfig__DatabaseId
              value: "StoreDatabase"
            - name: CosmosDbConfig__ContainerId
              value: "OrderContainer"
            - name: CosmosDbConfig__LeaseDatabaseId
              value: "StoreDatabase"
            - name: CosmosDbConfig__LeaseContainerId
              value: "OrderProcessorLeases"
            - name: CosmosDbConfig__ProcessorName
              value: "OrderProcessor"
            - name: CosmosDbConfig__OrderCount
              value: "1000"
            - name: CosmosDbConfig__IsSingleArticle
              value: "false"
            - name: CosmosDbConfig__Action
              value: "setup" #options: setup, teardown, generate